from VO.DDD import DDD_File

ddd1 = DDD_File(path="./data/1.ddd")
ddd1.Load()
ddd2 = DDD_File(path="./data/2.ddd")
ddd2.Load()
ddd3 = DDD_File(path="./data/3.ddd")
ddd3.Load()
ddd4 = DDD_File(path="./data/4.ddd")
ddd4.Load()
ddd5 = DDD_File(path="./data/5.ddd")
ddd5.Load()
ddd6 = DDD_File(path="./data/6.ddd")
ddd6.Load()

print(ddd1.GetHeader())
print(ddd2.GetHeader())
print(ddd3.GetHeader())
print(ddd4.GetHeader())
print(ddd5.GetHeader())
print(ddd6.GetHeader())

import matplotlib.pyplot as plt

plt.plot(ddd1.GetData()[0:ddd1.GetHeader().GetDepth()])
plt.show()
plt.plot(ddd2.GetData()[0:ddd2.GetHeader().GetDepth()])
plt.show()
plt.plot(ddd3.GetData()[0:ddd3.GetHeader().GetDepth()])
plt.show()
plt.plot(ddd4.GetData()[0:ddd4.GetHeader().GetDepth()])
plt.show()
plt.plot(ddd5.GetData()[0:ddd5.GetHeader().GetDepth()])
plt.show()
plt.plot(ddd6.GetData()[0:ddd6.GetHeader().GetDepth()])
plt.show()